galaxy_info:
  author: Aleksandr Bazhenov
  description: Installs and configures lxc/lxcfs on linux system
  license: MIT-0
  namespace: alexanderbazhenoff
  min_ansible_version: 2.9.0

  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Alpine
      versions:
        - all

  galaxy_tags:
    - lxc
    - lxcfs
    - containers
    - infrastructure

dependencies: []
