---

galaxy_info:
  role_name: zabbix_agent
  namespace: alexanderbazhenoff
  author: Aleksandr Bazhenov
  description: Installs zabbix agent and configure services, apps and platform autodiscovery.
  license: MIT-0
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: rhel
      versions:
        - all
    - name: Alpine
      versions:
        - all
    - name: Archlinux
      versions:
        - all

  galaxy_tags:
    - monitoring
    - zabbix
    - infrastructure
    - services
    - discovery
dependencies: []
