galaxy_info:
  role_name: postgresql
  namespace: alexanderbazhenoff
  author: Aleksandr Bazhenov
  description: Install and configure PostgreSQL.
  license: MIT-0
  min_ansible_version: 2.9.0
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Alpine
      versions:
        - all
  galaxy_tags:
    - postgresql
    - linux
    - database
dependencies: []
